<?php defined('SYSPATH') or die('No direct script access.');

    class Controller_Protocol extends Controller {
        protected $_vv = null;
        protected $_site_config= null;
        public function before()
        {
            parent::before(); // TODO: Change the autogenerated stub
            $this->_site_config = Kohana::$config->load('site');
            if(isset($this->_site_config['config']['view_version'])&&!empty($this->_site_config['config']['view_version'])){
                $this->_vv = $this->_site_config['config']['view_version'].'/';
            }else{
                $this->_vv = '';
            }
            //判断什么端

        }

        public function action_conten(){
			$protocolid = $this->request->query('num');
            $type = (isset($_GET['type'])&&!empty($_GET['type']))?$_GET['type']:null;
			//$type = isset($this->request->query('type')?$this->request->query('type'):null;
			//$oid = $this->request->query('oid');
			if(empty($protocolid) || $protocolid>5){
				$this->error('非法请求');
			}
            $typeNum = intval($type);
            if($typeNum<0 || $typeNum>3){
                $this->error('非法请求');
            }
            if($typeNum == 0){
                $type = '';
            }
            //合同判断
            if($protocolid==3&&!isset($_GET['list'])){
                //跳转合同和补充合同页面
                $this->redirect('/Protocol/protocolList?num='.$type);
                die;
            }else{
                $view = View::factory($this->_vv.'Protocol/protocol'.$protocolid.$type);
                $view->title=Kohana::$config->load('url.title.protocol'.$protocolid);
            }
            //判断是Android还是ios
            if(strpos($_SERVER['HTTP_USER_AGENT'], 'iPhone')||strpos($_SERVER['HTTP_USER_AGENT'], 'iPad')){
                if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger') !== false ) {
                    $view->client = "else";
                }else{
                    $view->client = "ios";
                }
                //$view->url = 'http://mp.weixin.qq.com/mp/redirect?url='.urlencode('https://itunes.apple.com/cn/app/kuai-jin/id1130326523?mt=8');
            }else if(strpos($_SERVER['HTTP_USER_AGENT'], 'Android')){
                if (strpos($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger') !== false ) {
                    $view->client = "else";
                }else{
                    $view->client = "android";
                }
            }else{
                $view->client = "else";
            }
            $this->response->body($view);
        }

        //合同列表
        public function action_protocolList(){
            $view = View::factory($this->_vv.'Protocol/protocolList');
            $view->title = '合同列表';
            $num = isset($_GET['num'])?$_GET['num']:3;

            $view->borrowUrl = '/Protocol/conten?num=3&list=1&type='.$num;
            $view->supplementUrl = '/Protocol/supplement';
            $this->response->body($view);
        }
        //补充协议
        public function action_supplement(){
            $view = View::factory($this->_vv.'Protocol/supplement');
            $view->title = '借款补充协议';
            $this->response->body($view);
        }


        //常遇问题
        public function action_Problem(){
            $view = View::factory($this->_vv.'Protocol/problem');
            $view->title = '快金常见问题与帮助';
            $this->response->body($view);
        }
        //智齿聊天系统
        public function action_Sobot(){
            $view = View::factory($this->_vv.'Protocol/sobot');
            $this->response->body($view);
        }
        //错误处理 发送到错误页面
        protected function error($error,$type=null){
            $view = View::factory('Error/index');
            $view->error = $error;
            $view->type = $type;
            $view->url = '/User/index?jump=no';
            $out = $view->render();
            exit( $out);
        }

        //借款攻略
        public function action_Raiders(){
            $view = View::factory($this->_vv.'Protocol/raiders');
            $this->response->body($view);
        }
}